# This tests that the sketch can compile on the target device esp32 nano
name: ESP-32 Super-Linter

on: push

jobs:
    super-lint:
        name: Build Arduino IDE Skectch
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
            with:
                submodules: 'recursive'
          - name: Arduino IDE
            uses: arduino/compile-sketches@v1
            with:
                fqbn: esp32:esp32:esp32doit-espduino
                libraries: |
                    - name: Aunit
                    - name: Stepper
                    - name: ESP-FlexyStepper
                sketch-paths: |
                    - ServerAndLED


              
