name: ESP-32 Super-Linter

on: push

jobs:
    super-lint:
        name: Build Arduino IDE Skectch
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
            with:
                submodules: 'recursive'
          - name: Arduino IDE
            uses: arduino/compile-sketches@v1
            with:
                fqbn: esp32:esp32:nano_nora
                sketch-paths: |
                    - ServerAndLED
                
            
              
