name: ESP-32 Super-Linter

on: push

jobs:
    super-lint:
        name: Build Arduino IDE Skectch
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
            with:
                submodules: 'recursive'
          - name: Arduino IDE
            uses: arduino/compile-sketches@v1
            with:
                fqbn: esp32:esp32:s3
                platforms:
                 -  name: esp32:esp32
                    source-url: source-url: https://dl.espressif.com/dl/package_esp32_index.json
                    libraries: |
                        - name: BLE
                        - name: EEPROM
                    sketch-paths: |
                        - ServerAndLED
