name: ESP-32 Super-Linter

on: push
    branches: [unit-testing-setup]

jobs:
    super-lint:
        name: Lint code base
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
            with:
                submodules: 'recursive'
          - name: esp-idf build
            uses: espressif/esp-idf-ci-action@v1
            with:
                esp_idf_version: v5.4
                target: esp32s3
                path: 'esp32-s3/builds/testing'
