# Tests on the functions using wokwi
name: ESP-32 Super-Linter
on: push
jobs:
    aunit-tests:
        name: Wokwi aunit tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                submodules: 'recursive'
            - name: Simulated esp32 tests
              uses: wokwi/wokwi-ci-action@v1
              with:
                token: ${{ secrets.WOKWI_CLI_TOKEN }}
                path: '/wokwi.toml'
                timeout: 10000
                run: apt get install arduino-cli;rm firmware/* -rf;arduino-cli compile -b esp32:esp32:esp32s3 ServerAndLED/ --build-path firmware/ --libraries libraries/ --libraries wokwi_lib --build-property build.extra_flags="-DTESTING -DWOKWI"; wokwi-cli > results.log; cat results.log





